name: run_tests

on:
  push:
    paths:
      - .github/workflows/run_tests.yml
      - investpy/**
      - tests/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip before package installation
      run: python -m pip install --upgrade pip
    - name: Install Python package dependencies
      run: pip install .
    - name: Install pytest requirements
      run: pip install investpy[tests]
    - name: Run pytest unit tests and check codecov
      run: pytest --cov-report term --cov=investpy tests/
